name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
        
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --shard ${{ matrix.shard }}/3 --reporter=html
      env:
        CI: true
        BASE_URL: https://www.saucedemo.com

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.shard }}
        path: |
          playwright-report
          test-results
        retention-days: 30

  merge-reports:
    # Run even if tests fail
    if: always()
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the workflow if merging fails
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Create report directory
      run: mkdir -p merged-report
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: playwright-report-*
        path: all-reports
        merge-multiple: false

    - name: List downloaded artifacts
      run: |
        echo "Contents of all-reports directory:"
        ls -R all-reports || echo "all-reports directory is empty"

    - name: Copy reports to merged directory
      run: |
        if [ -d "all-reports" ] && [ "$(ls -A all-reports)" ]; then
          echo "Found reports, copying to merged directory..."
          cp -r all-reports/*/* merged-report/ || echo "No reports to copy"
        else
          echo "No reports found to merge"
          echo "Creating empty report"
          echo "<html><body><h1>No test reports available</h1></body></html>" > merged-report/index.html
        fi

    - name: Upload merged report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-merged-report
        path: merged-report
        retention-days: 30
